"""add image key column to haircuts table

Revision ID: 78d788fa59ed
Revises: 91634d552419
Create Date: 2025-12-17 14:19:04.852295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d788fa59ed'
down_revision = '91634d552419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haircuts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_key', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haircuts', schema=None) as batch_op:
        batch_op.drop_column('image_key')

    # ### end Alembic commands ###
