"""create haircuts table

Revision ID: 91634d552419
Revises: 3cb7979b88d4
Create Date: 2025-12-14 21:41:20.903962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91634d552419'
down_revision = '3cb7979b88d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haircuts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=False),
    sa.Column('choosen_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('haircuts')
    # ### end Alembic commands ###
