"""add receipt_url and receipt_key columns to product_transactions and haircut_transactions table

Revision ID: 9c5203c5c193
Revises: a95b91aa7c83
Create Date: 2025-12-26 14:27:51.381590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5203c5c193'
down_revision = 'a95b91aa7c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haircut_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('receipt_key', sa.String(length=500), nullable=True))

    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('receipt_key', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_column('receipt_key')
        batch_op.drop_column('receipt_url')

    with op.batch_alter_table('haircut_transactions', schema=None) as batch_op:
        batch_op.drop_column('receipt_key')
        batch_op.drop_column('receipt_url')

    # ### end Alembic commands ###
