"""add expedition_cost column to product_transactions table

Revision ID: a95b91aa7c83
Revises: 67e75dd3bb4f
Create Date: 2025-12-25 12:37:53.429293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95b91aa7c83'
down_revision = '67e75dd3bb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expedition_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_column('expedition_cost')

    # ### end Alembic commands ###
