"""add shipping_address column in product_transactions table

Revision ID: c0a71fd36611
Revises: 6de18ac3454b
Create Date: 2025-12-21 20:52:11.720373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a71fd36611'
down_revision = '6de18ac3454b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
