"""create products table

Revision ID: cd8972957d5d
Revises: 78d788fa59ed
Create Date: 2025-12-17 20:23:50.744512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd8972957d5d'
down_revision = '78d788fa59ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('image_key', sa.String(length=255), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('haircuts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('image_key',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('haircuts', schema=None) as batch_op:
        batch_op.alter_column('image_key',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('products')
    # ### end Alembic commands ###
